# This file was generated by GoReleaser. DO NOT EDIT.
cask "loradex" do
  version "0.1.11"

  on_macos do
    on_intel do
      sha256 "511277d626ff034b83a41f6e8a88902677626b179f2f38d4f806e486b6ad3be8"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "441cf5014fd11e6dcfc7baf1eec5233392d8f5628de2d1e80060deb129a1548b"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8d67959c8f868e41d4f0ae9d8957064cba1be4e55abdd556a3cab5b7a154759d"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f55a9f479c65c91bb3837e8113e35aab0bb7a34d122e8e577083df429de3252"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "loradex"
  desc "Git for LoRAs from the command line — discover, train, convert, and publish LoRAs"
  homepage "https://github.com/keeandrews/loradex-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loradex"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loradex"]
    end
  end

  # No zap stanza required

end
