# This file was generated by GoReleaser. DO NOT EDIT.
cask "loradex" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "1012511ceb3a77db0109cdc5c72f0be32872c4a5ad55ae41f570709d81116a9b"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79461f57bba89819053d49d55ee48e4d7d76ab6a6b4d8f01a1bf3a431362b5ce"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "48d5bacab6f11dfe800cf9f6f4b0550a14c1cc87e5db1340e73a36fe9241bb0e"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f7dbd38ad9ab9cf2ddb32a560efc2a7ed74da179ac17f4a01c5eae9ee7dd499c"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "loradex"
  desc "Git for LoRAs from the command line — discover, train, convert, and publish LoRAs"
  homepage "https://github.com/keeandrews/loradex-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loradex"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loradex"]
    end
  end

  # No zap stanza required

end
