# This file was generated by GoReleaser. DO NOT EDIT.
cask "loradex" do
  version "0.1.13"

  on_macos do
    on_intel do
      sha256 "a67106a628d05b4b6ef4c1ac4070552ed533da09ce0b8f76d57cda5830843071"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8be94535a4da565c2846bfcf4945bbf2ef63de298edd9d3d2d1fa4e45e2361f8"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00b18c93bd33d0cc60919446e9432351b65e3bb916f8196222ad8d98adf8ee24"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "20c245b7c547b65a6f232981f05fa4925bb41d5851699a2c4ab1c30e33b07581"
      url "https://github.com/keeandrews/loradex-cli/releases/download/v#{version}/loradex_#{version}_linux_arm64.tar.gz"
    end
  end

  name "loradex"
  desc "Git for LoRAs from the command line — discover, train, convert, and publish LoRAs"
  homepage "https://github.com/keeandrews/loradex-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "loradex"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/loradex"]
    end
  end

  # No zap stanza required

end
